---
# Update the commands.cfg with the check_nrpe command
- name: Update the commands.cfg to include nrpe
  blockinfile:
    path: /usr/local/nagios/etc/objects/commands.cfg
    block: |
      define command{
        command_name check_nrpe
        command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
      }

 
