# Deploys a single webserver utilzing the Nginx demo site
---
- hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_html_demo_template_enable: true
    nginx_html_demo_template:
      default:
        template_file: www/index.html.j2
        html_file_name: demo-index.html
        html_file_location: /usr/share/nginx/html
        web_server_name: "{{ ansible_facts['hostname'] }}"


    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        port: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:80"
        server_name: web_server
        web_server_name: "{{ ansible_facts['hostname'] }}" 
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: demo-index.html
              autoindex: false
          http_demo_conf: true
