---
- hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  gather_facts: True
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_main_template_enable: true
    nginx_main_template:
      template_file: nginx.conf.j2
      conf_file_name: nginx.conf
      conf_file_location: /etc/nginx/
      user: nginx
      worker_processes: auto
      worker_rlimit_nofile: 5120
      error_level: warn
      worker_connections: 5120
      http_enable: true
      http_settings:
        keepalive_timeout: 65
        cache: true
        rate_limit: false
        keyval: false
      stream_enable: false
      http_global_autoindex: false


    nginx_html_demo_template_enable: true
    nginx_html_demo_template:
      default:
        template_file: www/index.html.j2
        html_file_name: demo-index.html
        html_file_location: /usr/share/nginx/html
        web_server_name: "{{ ansible_facts['hostname'] }}"


    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        port: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:{{ target_lb_ports }}"
        server_name: backend_server
        web_server_name: "{{ ansible_facts['hostname'] }}" 
        error_page: /usr/share/nginx/html
        autoindex: false
        web_server:
          locations:
            default:
              location: /
              html_file_location: /usr/share/nginx/html
              html_file_name: demo-index.html
              #add_header: Set-Cookie backend=backend1
              add_header: Set-Cookie {{sticky_backend_id }}
              proxy_set_sticky_header: X-Real-IP $remote_addr
              autoindex: false
          http_demo_conf: true

