---
- hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  roles:
  - role: ansible-role-systemd
    vars:
      unit_config:
      - name: "nginx"
        path: "/lib/systemd/system"
        Unit:
          # Description: nginx - high performance web server
          # Documentation: http://nginx.org/en/docs/
          After: network-online.target remote-fs.target nss-lookup.target
          Wants: network-online.target

        Service:
          Type: 'forking'
          PIDFile: '/var/run/nginx.pid'
          LimitNOFILE: '5120'
          LimitNPROC: '5120'
          ExecStart: '/usr/sbin/nginx -c /etc/nginx/nginx.conf'
          ExecReload: '/bin/kill -s HUP $MAINPID'
          ExecStop: '/bin/kill -s TERM $MAINPID'

        Install:
          WantedBy: 'multi-user.target'
  
  tasks:
    # Reload the system daemon after updating unit file
    - name: reload system daemon after changes
      shell: systemctl daemon-reload

    # Adjust the nginx user file open limits for a backend web server
    - name: configure system settings, file descriptors and number of threads
      pam_limits:
        domain: nginx
        limit_type: "{{item.limit_type}}"
        limit_item: "{{item.limit_item}}"
        value: "{{item.value}}"
      with_items:
        - { limit_type: '-', limit_item: 'nofile', value: 15360 }
        - { limit_type: '-', limit_item: 'nproc', value: 15360 }
        - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
        - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
    - name: reload settings from all system configuration files
      shell: sysctl --system


     # Completly stop and then start NGINX so NGINX pickups new values
    - name: stop nginx
      shell: systemctl stop nginx

    - name: start nginx
      shell: systemctl start nginx

