# Uses https://github.com/cloudalchemy/ansible-prometheus
# Installs Prometheus 2.15.2
# Install systemd unit file
---
- hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  roles:
    - role: ansible-prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - 192.168.1.3:9100
        labels:
          env: monitoring
