---
- hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  vars:
    add_user: some_user
  tasks:
    - name: Add the user add_user include bash shell and add to sudo
      user:
        name: "{{item}}"
        shell: /bin/bash
        groups: users,sudo
        append: yes
      with_items:
        - "{{ add_user }}"

    - name: Add the authorized users keys to user.
      authorized_key: 
        user: "{{ add_user }}" 
        key: "{{item}}"
      with_file:
        - /home/developer/temp/authorized_keys

    - name: Allow user's group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%{{add_user}}'
        line: '%{{add_user}} ALL=(ALL) NOPASSWD: ALL'

    - name: Add sudoers users to group
      user: 
        name: "{{ add_user }}"  
        groups: sudo 
        append: yes 
        state: present 
        createhome: yes
