# Verifies the install and outputs results to ansible.
# Sets the environment var PATH since it's impossible to source /etc/profile

- name: Verify go install
  become_user: root
  command: go version
  environment: 
    PATH: "/usr/local/go/bin"
  register: go_ver

- name: Debug go version
  debug:
    var: go_ver
    verbosity: 0

- name: Verify go environment variables
  shell: go env
  environment:
    PATH: "/usr/local/go/bin"
  register: go_env

- name: Debug go environment
  debug:
    var: go_env
    verbosity: 0
