# Updates hostname to match inventory name. 
# Updates etc hosts with local ip and inventory hostname
# Updates apt
# Updates apt packages

---
- hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_hostname
    - debug: var=inventory_hostname

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Update hostname to inventory hostname
      hostname:
       name: "{{ inventory_hostname }}"
  
    - name: Remove lines with unwanted occurrences of localip hostname
      lineinfile: dest=/etc/hosts
                  regexp="^{{ ansible_default_ipv4.address }}"
                  state=absent

    - name: Build hosts file
      lineinfile: dest=/etc/hosts 
                  line="{{ ansible_default_ipv4.address }} {{ ansible_hostname}}" state=present insertafter="127.0.0.1 localhost*"
      when: ansible_default_ipv4.address is defined
