# Removes sshd_config LISTEN 0.0.0.0
# Adds sshd_config LISTEN {{ local_ip }}
# Restartes sshd in check mode (so you don't happen to loose conectivty)
---
- hosts: "{{ target_host }}"
  remote_user: "{{ target_user }}"
  tasks:

    - name: Remove lines with unwanted occurrences of ListenAddress
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^ListenAddress (?!1.2.3.4)"
                  state=absent

    - name: Listen on public and private IP
      lineinfile: dest=/etc/ssh/sshd_config
                  line={{ item.line }}
                  insertafter={{ item.insertafter }}
      with_items:
        - { line: "ListenAddress {{ ansible_default_ipv4.address }}", insertafter: "^#?#ListenAddress 0.0.0.0" }

    - name: Restart systemctl sshd in check mode only
      systemd:
        name: sshd
        state: reloaded
      check_mode: yes
